### ISSUE TITLE
Consider swithing the Exit toolbar button with Favorites

### ISSUE THREAD

**Issue by meirtsvi** [meirtsvi/WazeWP7#2]
Since WP7 limits the number of buttons to 4 in the toolbar we cannot have both Favorites and Exit button (unless we remove some other button).
Assuming Favorites function is more common than Exit (need to check this up as most users may be anonymous thus not having favorites kept on the server), the Exit button should be replaced with Favorites.

**Comment by meirtsvi** [comment]
Done

**Comment by thesourcerer** [comment]
Looking at the code it seems the button now fires "מקומות שמורים" instead of "המועדפים שלי"/"My favorites"..
isn't favorites a better option then saved locations?
