### ISSUE TITLE
Suggestion:Hiding upper systray

### ISSUE THREAD

**Issue by thesourcerer** [meirtsvi/WazeWP7#20]
Suggesting to change shell:SystemTray.IsVisible="True" to False.
The upper systray bar is taking up space, and is not very handy when driving.
it even more important when swtching to landscape, as the buttom app bar also takes space,
and we are left with a narrow map.

**Comment by enjibby** [comment]
It may also be an idea to, instead of setting shell:SystemTray.IsVisible="False", to set shell:SystemTray.Mode=ApplicationBarMode::Mini. I believe this is a new thing in Mango.

**Comment by thesourcerer** [comment]
shell:SystemTray does not have a Mode Property in mango
http://msdn.microsoft.com/en-us/library/ff626688(v=VS.92).aspx

if you are reffering to 
ApplicationBar.Mode = ApplicationBarMode.Minimized;
Then I wouldn't think it is suitable for this kind of app for 2 reasons:
1. it will be very hard to press on the ... while driving.
2. on landscape mode the AppBar will force default mode anyway...

I believe this is good for apps that force you to use portrait mode, and use while you ar enot driving...
