### ISSUE TITLE
Back button on map screen should exit Waze (with confirmation dialog)

### ISSUE THREAD

**Issue by meirtsvi** [meirtsvi/WazeWP7#26]
Currently the back button brings the user back to the map. We want to change the behavior so that pressing Back on non map windows will continue to bring the user to the map window but when pressing Back on the map menu, a dialog will appear asking the user whether to exit Waze or not.

**Comment by ee61re** [comment]
This issue can be closed - fixed in 0.9.8.7

**Comment by meirtsvi** [comment]
fixed by Eli Ofek
