### ISSUE TITLE
When playing directions, mute currently playing music and restore it back once finished

### ISSUE THREAD

**Issue by meirtsvi** [meirtsvi/WazeWP7#43]
Currently, when playing music in the background (Tune-in Radio, for instance) Waze will stop the music upon giving directions (or any other sound it makes) and will not bring it back…

The ideal behavior is just lowering the volume of the background music, but I can settle for anything that doesn’t plain stops the music

**Comment by thesourcerer** [comment]
Yes, this is a problem...
Couldn't figure out a way to solve yet.
according to this 
http://msdn.microsoft.com/en-us/library/hh394039(v=VS.92).aspx
it might not be possible.
MediaElement and the BackgroundAudioPlayer

Care must be taken when mixing BackgroundAudioPlayer and MediaElement for audio playback.
1.
Close must be called before switching to MediaElement playback.

2.
There is only one media queue. Your application cannot pause background audio, play something with MediaElement then resume the background audio stream.

**Comment by meirtsvi** [comment]
The first thing we might need to do here is to convert the SL media player usage with playing using XNA classes. This might help us in pausing the currently played music (or even access it), play our sounds and resume the original music.
I had code from someone that replaces the SL with XNA but it was good only for the 1st wav file. Playing several WAV files in a row is not trivial in XNA - you need to wait until the currently played one finished and only then play the next one. Waze is not built that way and to make things worse, we cannot add Sleep with the length of the WAV since it's the main thread and pausing it pauses all Waze (yes, I tried)

**Comment by thesourcerer** [comment]
Just tried that myself using SoundEffect.
http://msdn.microsoft.com/en-us/library/dd282421(v=xnagamestudio.35).aspx
I did have to add sleep to avoind the instance from being collected.
(I can do it witout sleep if we keep the last instance rooted statically, but sleep looks like it's working fine...)

**Comment by meirtsvi** [comment]
Eli Ofek fixed that by playing the directions along with the currently playing music
