### ISSUE TITLE
Search on Yellow Pages in addition like official app does

### ISSUE THREAD

**Issue by Lidanha** [meirtsvi/WazeWP7#70]
The ported application is simply work of art.

The only thing that I'm actually missing right now is that the search results will contain Yellow Pages data in addition to the Waze's street search.

When you search in Waze for iOS or Waze for Android you receive results from the Yellow Pages (In Israel at least) if there are any. The ported WP7 version is currently missing that feature.

I hope it's somewhere in the roadmap.

Good work Meir and the rest of the guys, Thumbs up!

**Comment by meirtsvi** [comment]
We have that implemented. Simply swipe the search results screen right or left and you'll have the yellow pages results

**Comment by Lidanha** [comment]
Oh, My bad... It looks like it's working great. Thank you Meir.
