### ISSUE TITLE
Select Language without any options

### ISSUE THREAD

**Issue by allancm** [meirtsvi/WazeWP7#72]
Hello, I just downloaded the last version and I deployed to the WP7 device (lumia 900).

It shows the splash window correctly, then it displays the "Initializing please wait" message, and then a window with a title "Please select language" without any option.
I try to select blind options but it is not possible.  The only thing I can do is go back and it shows the blue car sprite and not map at all.

I live in Costa Rica.

Thanks for any help.

**Comment by meirtsvi** [comment]
I tried to browse live map from Waze web site for Costa Rica and found no map exist. Maybe this is the problem?

**Comment by allancm** [comment]
I can use Waze with iPhones and androids with no problems at all here.

**Comment by meirtsvi** [comment]
When you press Back, do you have the ellipsis menu ("..."), if so, please scroll down and press on Send Logs. I will try to take a look at the logs

**Comment by allancm** [comment]
After running the applications several times, the menu of the language appeared with the options, and the map is showing up right now.  (I did not install a new version).

The application is now running and I can see the incidents and the average of the speed by sections of the roads as expected.  So everything seems working fine, except some dialogs that may be related with some work in progress.

But great effort for this version of the app, thanks for your work.
