### ISSUE TITLE
Update for Win10

### ISSUE THREAD

**Issue by eried** [meirtsvi/WazeWP7#75]
hey! are you thinking on uploading this for the new phones? rebrand it and sell it, screw google fuckers ;)

**Comment by Priednis** [comment]
You know there is a version of Waze available for windows 10...
https://www.microsoft.com/en-us/store/p/waze/9wzdncrfj2m3
It is however (as it is sadly usually the case) a bit outdated compared to other platforms...

**Comment by eried** [comment]
No I did not, I'll check 👍
